/* first.c generated by valac 0.40.23, the Vala compiler
 * generated from first.vala, do not modify */



#include <glib.h>
#include <glib-object.h>




void _vala_main (void);


void
_vala_main (void)
{
	g_print ("Hello World! This is Vala!");
}


int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}



