/* matrix.c generated by valac 0.40.23, the Vala compiler
 * generated from matrix.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <sys/time.h>
#include <string.h>



extern gint dimension;
gint dimension = 0;

#define step 32
#define MAX_DIMENSION (2048 * 4)
void step_dimension (void);
gdouble gtod (void);
void multiply_matrix (gdouble* matrix_a,
                      int matrix_a_length1,
                      int matrix_a_length2,
                      gdouble* matrix_b,
                      int matrix_b_length1,
                      int matrix_b_length2,
                      gdouble* matrix_c,
                      int matrix_c_length1,
                      int matrix_c_length2);
void print_matrix (gdouble* matrix,
                   int matrix_length1,
                   int matrix_length2,
                   gint dimension);
void random_matrix (gdouble* matrix,
                    int matrix_length1,
                    int matrix_length2,
                    gint dimension);
void collect_info (gdouble t_start,
                   gdouble t_end,
                   gdouble gflops);
void _vala_main (void);


void
step_dimension (void)
{
	gint _tmp0_;
	_tmp0_ = dimension;
	if (_tmp0_ < 256) {
		gint _tmp1_;
		_tmp1_ = dimension;
		dimension = _tmp1_ + step;
	} else {
		gint _tmp2_;
		_tmp2_ = dimension;
		if (_tmp2_ < 512) {
			gint _tmp3_;
			_tmp3_ = dimension;
			dimension = _tmp3_ + (step * 2);
		} else {
			gint _tmp4_;
			_tmp4_ = dimension;
			if (_tmp4_ < 1024) {
				gint _tmp5_;
				_tmp5_ = dimension;
				dimension = _tmp5_ + (step * 4);
			} else {
				gint _tmp6_;
				_tmp6_ = dimension;
				if (_tmp6_ < 2048) {
					gint _tmp7_;
					_tmp7_ = dimension;
					dimension = _tmp7_ + (step * 8);
				} else {
					gint _tmp8_;
					_tmp8_ = dimension;
					if (_tmp8_ < 4096) {
						gint _tmp9_;
						_tmp9_ = dimension;
						dimension = _tmp9_ + (step * 16);
					} else {
						gint _tmp10_;
						_tmp10_ = dimension;
						dimension = _tmp10_ + (step * 32);
					}
				}
			}
		}
	}
}


gdouble
gtod (void)
{
	gdouble result = 0.0;
	struct timeval act_time = {0};
	struct timeval _tmp0_;
	time_t _tmp1_;
	struct timeval _tmp2_;
	glong _tmp3_;
	memset (&act_time, 0, sizeof (struct timeval));
	gettimeofday (&act_time, NULL);
	_tmp0_ = act_time;
	_tmp1_ = _tmp0_.tv_sec;
	_tmp2_ = act_time;
	_tmp3_ = _tmp2_.tv_usec;
	result = ((gdouble) _tmp1_) + (((gdouble) _tmp3_) / 1000000.0);
	return result;
}


void
multiply_matrix (gdouble* matrix_a,
                 int matrix_a_length1,
                 int matrix_a_length2,
                 gdouble* matrix_b,
                 int matrix_b_length1,
                 int matrix_b_length2,
                 gdouble* matrix_c,
                 int matrix_c_length1,
                 int matrix_c_length2)
{
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_;
				gint _tmp3_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = dimension;
				if (!(_tmp2_ < _tmp3_)) {
					break;
				}
				{
					gint k = 0;
					k = 0;
					{
						gboolean _tmp4_ = FALSE;
						_tmp4_ = TRUE;
						while (TRUE) {
							gint _tmp6_;
							gint _tmp7_;
							if (!_tmp4_) {
								gint _tmp5_;
								_tmp5_ = k;
								k = _tmp5_ + 1;
							}
							_tmp4_ = FALSE;
							_tmp6_ = k;
							_tmp7_ = dimension;
							if (!(_tmp6_ < _tmp7_)) {
								break;
							}
							{
								gint j = 0;
								j = 0;
								{
									gboolean _tmp8_ = FALSE;
									_tmp8_ = TRUE;
									while (TRUE) {
										gint _tmp10_;
										gint _tmp11_;
										gint _tmp12_;
										gint _tmp13_;
										gint _tmp14_;
										gint _tmp15_;
										gdouble _tmp16_;
										gint _tmp17_;
										gint _tmp18_;
										gdouble _tmp19_;
										if (!_tmp8_) {
											gint _tmp9_;
											_tmp9_ = j;
											j = _tmp9_ + 1;
										}
										_tmp8_ = FALSE;
										_tmp10_ = j;
										_tmp11_ = dimension;
										if (!(_tmp10_ < _tmp11_)) {
											break;
										}
										_tmp12_ = i;
										_tmp13_ = j;
										_tmp14_ = i;
										_tmp15_ = k;
										_tmp16_ = matrix_a[(_tmp14_ * matrix_a_length2) + _tmp15_];
										_tmp17_ = k;
										_tmp18_ = j;
										_tmp19_ = matrix_b[(_tmp17_ * matrix_b_length2) + _tmp18_];
										matrix_c[(_tmp12_ * matrix_c_length2) + _tmp13_] += _tmp16_ * _tmp19_;
									}
								}
							}
						}
					}
				}
			}
		}
	}
}


void
print_matrix (gdouble* matrix,
              int matrix_length1,
              int matrix_length2,
              gint dimension)
{
	{
		gint row = 0;
		row = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = row;
					row = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = row;
				if (!(_tmp2_ < dimension)) {
					break;
				}
				{
					gint value = 0;
					value = 0;
					{
						gboolean _tmp3_ = FALSE;
						_tmp3_ = TRUE;
						while (TRUE) {
							gint _tmp5_;
							gint _tmp6_;
							gint _tmp7_;
							gdouble _tmp8_;
							if (!_tmp3_) {
								gint _tmp4_;
								_tmp4_ = value;
								value = _tmp4_ + 1;
							}
							_tmp3_ = FALSE;
							_tmp5_ = value;
							if (!(_tmp5_ < dimension)) {
								break;
							}
							_tmp6_ = row;
							_tmp7_ = value;
							_tmp8_ = matrix[(_tmp6_ * matrix_length2) + _tmp7_];
							g_print ("%f ", _tmp8_);
						}
					}
				}
				g_print ("\n");
			}
		}
	}
}


void
random_matrix (gdouble* matrix,
               int matrix_length1,
               int matrix_length2,
               gint dimension)
{
	{
		gint row = 0;
		row = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = row;
					row = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = row;
				if (!(_tmp2_ < dimension)) {
					break;
				}
				{
					gint value = 0;
					value = 0;
					{
						gboolean _tmp3_ = FALSE;
						_tmp3_ = TRUE;
						while (TRUE) {
							gint _tmp5_;
							gint _tmp6_;
							gint _tmp7_;
							if (!_tmp3_) {
								gint _tmp4_;
								_tmp4_ = value;
								value = _tmp4_ + 1;
							}
							_tmp3_ = FALSE;
							_tmp5_ = value;
							if (!(_tmp5_ < dimension)) {
								break;
							}
							_tmp6_ = row;
							_tmp7_ = value;
							matrix[(_tmp6_ * matrix_length2) + _tmp7_] = (gdouble) g_random_double ();
						}
					}
				}
			}
		}
	}
}


void
collect_info (gdouble t_start,
              gdouble t_end,
              gdouble gflops)
{
	gint _tmp0_;
	_tmp0_ = dimension;
	g_print ("Dim: %4d runtime: %7.4fs GFLOP/s: %0.2f\n", _tmp0_, t_end - t_start, gflops);
}


void
_vala_main (void)
{
	gdouble t_start = 0.0;
	gdouble t_end = 0.0;
	gdouble gflops = 0.0;
	while (TRUE) {
		gint _tmp0_;
		gdouble* matrix_a = NULL;
		gint _tmp1_;
		gint _tmp2_;
		gdouble* _tmp3_;
		gint matrix_a_length1;
		gint matrix_a_length2;
		gdouble* matrix_b = NULL;
		gint _tmp4_;
		gint _tmp5_;
		gdouble* _tmp6_;
		gint matrix_b_length1;
		gint matrix_b_length2;
		gdouble* matrix_c = NULL;
		gint _tmp7_;
		gint _tmp8_;
		gdouble* _tmp9_;
		gint matrix_c_length1;
		gint matrix_c_length2;
		gdouble* _tmp10_;
		gint _tmp10__length1;
		gint _tmp10__length2;
		gint _tmp11_;
		gdouble* _tmp12_;
		gint _tmp12__length1;
		gint _tmp12__length2;
		gint _tmp13_;
		gdouble* _tmp14_;
		gint _tmp14__length1;
		gint _tmp14__length2;
		gdouble* _tmp15_;
		gint _tmp15__length1;
		gint _tmp15__length2;
		gdouble* _tmp16_;
		gint _tmp16__length1;
		gint _tmp16__length2;
		gint _tmp17_;
		gint _tmp18_;
		gint _tmp19_;
		gdouble _tmp20_;
		gdouble _tmp21_;
		gdouble _tmp22_;
		gdouble _tmp23_;
		gdouble _tmp24_;
		_tmp0_ = dimension;
		if (!(_tmp0_ < MAX_DIMENSION)) {
			break;
		}
		step_dimension ();
		_tmp1_ = dimension;
		_tmp2_ = dimension;
		_tmp3_ = g_new0 (gdouble, _tmp1_ * _tmp2_);
		matrix_a = _tmp3_;
		matrix_a_length1 = _tmp1_;
		matrix_a_length2 = _tmp2_;
		_tmp4_ = dimension;
		_tmp5_ = dimension;
		_tmp6_ = g_new0 (gdouble, _tmp4_ * _tmp5_);
		matrix_b = _tmp6_;
		matrix_b_length1 = _tmp4_;
		matrix_b_length2 = _tmp5_;
		_tmp7_ = dimension;
		_tmp8_ = dimension;
		_tmp9_ = g_new0 (gdouble, _tmp7_ * _tmp8_);
		matrix_c = _tmp9_;
		matrix_c_length1 = _tmp7_;
		matrix_c_length2 = _tmp8_;
		_tmp10_ = matrix_a;
		_tmp10__length1 = matrix_a_length1;
		_tmp10__length2 = matrix_a_length2;
		_tmp11_ = dimension;
		random_matrix (_tmp10_, _tmp10__length1, _tmp10__length2, _tmp11_);
		_tmp12_ = matrix_b;
		_tmp12__length1 = matrix_b_length1;
		_tmp12__length2 = matrix_b_length2;
		_tmp13_ = dimension;
		random_matrix (_tmp12_, _tmp12__length1, _tmp12__length2, _tmp13_);
		t_start = gtod ();
		_tmp14_ = matrix_a;
		_tmp14__length1 = matrix_a_length1;
		_tmp14__length2 = matrix_a_length2;
		_tmp15_ = matrix_b;
		_tmp15__length1 = matrix_b_length1;
		_tmp15__length2 = matrix_b_length2;
		_tmp16_ = matrix_c;
		_tmp16__length1 = matrix_c_length1;
		_tmp16__length2 = matrix_c_length2;
		multiply_matrix (_tmp14_, _tmp14__length1, _tmp14__length2, _tmp15_, _tmp15__length1, _tmp15__length2, _tmp16_, _tmp16__length1, _tmp16__length2);
		t_end = gtod ();
		_tmp17_ = dimension;
		_tmp18_ = dimension;
		_tmp19_ = dimension;
		_tmp20_ = t_end;
		_tmp21_ = t_start;
		gflops = ((((((gdouble) 2) * _tmp17_) * _tmp18_) * _tmp19_) / 1000000000.0) / (_tmp20_ - _tmp21_);
		_tmp22_ = t_start;
		_tmp23_ = t_end;
		_tmp24_ = gflops;
		collect_info (_tmp22_, _tmp23_, _tmp24_);
		matrix_c = (g_free (matrix_c), NULL);
		matrix_b = (g_free (matrix_b), NULL);
		matrix_a = (g_free (matrix_a), NULL);
	}
}


int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}



